environments:
- name: env-dev
  namespace: bp-dev-hg-en3-cl1-sg3
  path: examples/helm/testchart
  project: ''
  stage: one
  targetRevision: moreadv
  url: https://kubernetes.default.svc
  valueFiles: dev-values.yaml
- name: env-qa
  namespace: bp-qa-hg-en3-cl1-sg3
  path: examples/helm/testchart
  project: ''
  stage: two
  targetRevision: moreadv
  url: https://kubernetes.default.svc
  valueFiles: qa-values.yaml
- name: env-prod
  namespace: bp-prod-hg-en3-cl1-sg3
  path: examples/helm/testchart
  project: ''
  stage: three
  targetRevision: moreadv
  url: https://kubernetes.default.svc
  valueFiles: dev-values.yaml,qa-values.yaml
helm: true
name: bp-hg-en3-cl1-sg3
namespace: ''
path: ''
plainYAML: false
project: default
repoURL: https://github.com/gopaljayanthi/appset-chart.git
stages:
  key: stage
  values:
  - one
  - two
  - three
targetRevision: ''
url: ''
