environments:
- name: env-dev
  namespace: bp-dev-ma-job-py-en2-cl1-sg3
  path: examples/plainYAML/engineering-dev
  project: ''
  stage: one
  targetRevision: moreadv
  url: https://kubernetes.default.svc
- name: env-prod-approval
  namespace: bp-env-prod-approval
  path: k8sjob
  project: ''
  stage: two
  targetRevision: moreadv
  url: https://kubernetes.default.svc
- name: env-prod
  namespace: bp-env-prod
  path: examples/plainYAML/engineering-prod
  project: ''
  stage: three
  targetRevision: moreadv
  url: https://kubernetes.default.svc
helm: false
name: bp-ma-job-py-en2-cl1-sg3
namespace: ''
path: ''
plainYAML: true
project: default
repoURL: https://github.com/gopaljayanthi/appset-chart.git
stages:
  key: stage
  values:
  - one
  - two
  - three
targetRevision: ''
url: ''
