#set only one of the following to be true, the method of deployment
plainYAML: true
helm: false
#kustomize: false # this template is not yet ready

#common variables for all environments

name: py-en2-cl1-sg2
project: default
repoURL: https://github.com/gopaljayanthi/appset-chart.git      # Can point to either a Helm chart repo or a git repo.

# variables for specific environments
environments:
- name: env-dev
  stage: one
  namespace: dev-py-en2-cl1-sg2
  url: https://kubernetes.default.svc
  path: examples/plainYAML/engineering-dev                            # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.
  targetRevision: stages                                                # For Helm, this refers to the chart version.
- name: env-prod
  stage: two
  namespace: prod-py-en2-cl1-sg2
  url: https://kubernetes.default.svc
  path: examples/plainYAML/engineering-prod          # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.
  targetRevision: stages                                                # For Helm, this refers to the chart version.

stages:
  key: envLabel
  values:
  - one
  - two