apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: "https://github.com/OpsMx/argocd-app-onboarding.git"
        revision: "main"
        files:
          - path: configs/nginx/config.json
  template:
    metadata:
      name: '{{.appName}}'
    spec:
      project: default
      sources:
        - repoURL: '{{.repoURL}}'
          targetRevision: '{{.targetRevision}}'
          chart: '{{.chart}}'
          helm:
            releaseName: '{{.appName}}'
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{.namespace}}'
