---
# Source: k8sinfra-chart/templates/k8sinfra-appset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-k8sinfra-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: "https://github.com/gopaljayanthi/appset-chart.git"
        revision: "moreadv"
        files:
          - path: configs/nginx/config.json
  template:
    metadata:
      name: '{{.appName}}'
    spec:
      project: default
      sources:
        - repoURL: '{{.repoURL}}'
          targetRevision: '{{.targetRevision}}'
          chart: '{{.chart}}'
          helm:
            releaseName: '{{.appName}}'
            valueFiles:
              - "$values/{{.valuesPath}}"
              - "$values/{{.valuesOverlayPath}}"
        - repoURL: https://github.com/gopaljayanthi/appset-chart.git
          targetRevision: moreadv
          ref: values
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{.namespace}}'
