apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  labels: 
    name: another
    fame: another
    game: another
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
