apiVersion: v1
kind: Service
metadata:
  labels:
    name: something
    address: here
    role: devopstopsmx
    pole: devopstopsmx
  name: guestbook-ui
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
