resources:
  - ./k8s/manifests/deployment.yaml
  - ./k8s/manifests/namespace.yaml
  - ./k8s/manifests/service.yaml
  - ./k8s/manifests/ingress.yaml
  - ./k8s/manifests/rbac.yaml

configMapGenerator:
  - name: appset-ui
    namespace: appset-ui
    files:
      - app.py=./src/app.py